### ISSUE TITLE
Definir Componentes Tailwind

### ISSUE THREAD

**Issue by marcodotcastro** [desenvolvendo-me/developer-evolution#74]
- [x] Listar
- [x] Detalhar
- [x] Cadastrar
- [x] Atualizar

**Comment by PhilipeeX** [comment]
Componente definido para cadastro, componente 1 conforme votação:
![Image](https://github.com/desenvolvendo-me/developer-evolution/assets/85847179/e22de9ae-95c2-48e5-bfd4-532697b7e1a3)
[Floating labels - cadastrar](https://flowbite.com/docs/components/forms/#floating-labels)

**Comment by gudiao21** [comment]
![Image](https://github.com/desenvolvendo-me/developer-evolution/assets/72048128/88fafd1d-ad03-46aa-8a9a-78c71f89d04f)

https://flowbite.com/blocks/application/crud-update-forms/

**Comment by ansulima** [comment]
https://tailwindcomponents.com/component/list-order-product

![Image](https://github.com/desenvolvendo-me/developer-evolution/assets/81773627/9366b336-8b7c-47e9-97cc-0e78c5a8cc47)

**Comment by gugovisk** [comment]
https://flowbite.com/blocks/application/crud-read-sections/

**Comment by marcodotcastro** [comment]
Sugestão para Index: https://flowbite.com/blocks/application/advanced-tables/
